apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-user-deployment
  labels:
    app: auth-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-user
  template:
    metadata:
      labels:
        app: auth-user
    spec:
      containers:
      - name: auth-user
        image: lucmigue/auth-user
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-user-service
spec:
  type: NodePort
  selector:
    app: auth-user
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001