apiVersion: apps/v1
kind: Deployment
metadata:
  name: fillter-deployment
  labels:
    app: fillter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fillter
  template:
    metadata:
      labels:
        app: fillter
    spec:
      containers:
      - name: fillter
        image: lucmigue/fillter
        ports:
        - containerPort: 9090
        env:
        - name: DATABASE_URL
          value: "mongodb+srv://darkness:root@projlp2.3qlyony.mongodb.net/?retryWrites=true&w=majority&appName=ProjLP2"
---
apiVersion: v1
kind: Service
metadata:
  name: fillter-service
spec:
  type: NodePort
  selector:
    app: fillter
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002