apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: lucmigue/profile
        ports:
        - containerPort: 8800

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: NodePort
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
      nodePort: 30000 # Porta do host onde o serviço estará disponível (opcionalmente configurável)


