apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-up-deployment
  labels:
    app: sign-up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-up
  template:
    metadata:
      labels:
        app: sign-up
    spec:
      containers:
      - name: sign-up
        image: lucmigue/sign-up
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: sign-up-service
spec:
  type: NodePort
  selector:
    app: sign-up
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30003